# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "PLACE_HERE_UR_ETAPI_TOKEN"
          replace: "${{ secrets.ETAPITOKEN }}"
          regex: false
          
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "https://ur_server:8080"
          replace: "${{ secrets.TRILIUMURL }}"
          regex: false
          
      - name: Installing libs
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10.7"

      - run: python3 -m pip install -r requirements.txt 
        
      - name: Running the script
        run: python3 start.py
